[project]
name = "gym-tracker-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.121.0",
    "passlib[bcrypt]>=1.7.4",
    "sqlmodel>=0.0.27",
    "uvicorn>=0.38.0",
]
